CREATE SCHEMA "DB_SYSTEM" AUTHORIZATION "SYSDBA";

DROP TABLE IF EXISTS "DB_SYSTEM"."CODE_COLUMN_CONFIG";
DROP TABLE IF EXISTS "DB_SYSTEM"."CODE_GEN_CONFIG";
DROP TABLE IF EXISTS "DB_SYSTEM"."MNT_APP";
DROP TABLE IF EXISTS "DB_SYSTEM"."MNT_DATABASE";
DROP TABLE IF EXISTS "DB_SYSTEM"."MNT_DEPLOY";
DROP TABLE IF EXISTS "DB_SYSTEM"."MNT_DEPLOY_HISTORY";
DROP TABLE IF EXISTS "DB_SYSTEM"."MNT_DEPLOY_SERVER";
DROP TABLE IF EXISTS "DB_SYSTEM"."MNT_SERVER";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_DEPT";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_DICT";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_DICT_DETAIL";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_JOB";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_LOG";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_MENU";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_QUARTZ_JOB";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_QUARTZ_LOG";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_ROLE";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_ROLES_DEPTS";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_ROLES_MENUS";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_USER";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_USERS_JOBS";
DROP TABLE IF EXISTS "DB_SYSTEM"."SYS_USERS_ROLES";
DROP TABLE IF EXISTS "DB_SYSTEM"."TOOL_ALIPAY_CONFIG";
DROP TABLE IF EXISTS "DB_SYSTEM"."TOOL_EMAIL_CONFIG";
DROP TABLE IF EXISTS "DB_SYSTEM"."TOOL_LOCAL_STORAGE";
DROP TABLE IF EXISTS "DB_SYSTEM"."TOOL_QINIU_CONFIG";
DROP TABLE IF EXISTS "DB_SYSTEM"."TOOL_QINIU_CONTENT";

CREATE TABLE "DB_SYSTEM"."CODE_COLUMN_CONFIG"
(
"COLUMN_ID" VARCHAR(32) NOT NULL,
"TABLE_NAME" VARCHAR(180),
"COLUMN_NAME" VARCHAR(255),
"COLUMN_TYPE" VARCHAR(255),
"DICT_NAME" VARCHAR(255),
"EXTRA" VARCHAR(255),
"FORM_SHOW" BIT,
"FORM_TYPE" VARCHAR(255),
"KEY_TYPE" VARCHAR(255),
"LIST_SHOW" BIT,
"NOT_NULL" BIT,
"QUERY_TYPE" VARCHAR(2),
"REMARK" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("COLUMN_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."CODE_COLUMN_CONFIG" IS '代码生成字段信息存储';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."COLUMN_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."COLUMN_NAME" IS '数据库字段名称';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."COLUMN_TYPE" IS '数据库字段类型';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."DICT_NAME" IS '字典名称';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."EXTRA" IS '字段额外的参数';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."FORM_SHOW" IS '是否表单显示';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."FORM_TYPE" IS '表单类型';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."KEY_TYPE" IS '数据库字段键类型';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."LIST_SHOW" IS '是否在列表显示';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."NOT_NULL" IS '是否必填';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."QUERY_TYPE" IS '查询 1:模糊 2：精确';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."REMARK" IS '数据库字段描述';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_COLUMN_CONFIG"."TABLE_NAME" IS '表名';


CREATE  INDEX "INDEX871470155215600" ON "DB_SYSTEM"."CODE_COLUMN_CONFIG"("TABLE_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871470160687100" ON "DB_SYSTEM"."CODE_COLUMN_CONFIG"("COLUMN_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."CODE_GEN_CONFIG"
(
"CONFIG_ID" VARCHAR(32) NOT NULL,
"TABLE_NAME" VARCHAR(255),
"AUTHOR" VARCHAR(255),
"COVER" BIT,
"MODULE_NAME" VARCHAR(255),
"PACK" VARCHAR(255),
"PATH" VARCHAR(255),
"API_PATH" VARCHAR(255),
"PREFIX" VARCHAR(255),
"API_ALIAS" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("CONFIG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."CODE_GEN_CONFIG" IS '代码生成器配置';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."API_ALIAS" IS '接口名称';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."API_PATH" IS '前端Api文件路径';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."AUTHOR" IS '作者';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."CONFIG_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."COVER" IS '是否覆盖';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."MODULE_NAME" IS '模块名称';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."PACK" IS '至于哪个包下';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."PATH" IS '前端代码生成的路径';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."PREFIX" IS '表前缀';
COMMENT ON COLUMN "DB_SYSTEM"."CODE_GEN_CONFIG"."TABLE_NAME" IS '表名';


CREATE  INDEX "IDX_TABLE_NAME" ON "DB_SYSTEM"."CODE_GEN_CONFIG"("TABLE_NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871470128005000" ON "DB_SYSTEM"."CODE_GEN_CONFIG"("CONFIG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."MNT_APP"
(
"APP_ID" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(255),
"UPLOAD_PATH" VARCHAR(255),
"DEPLOY_PATH" VARCHAR(255),
"BACKUP_PATH" VARCHAR(255),
"PORT" INT,
"START_SCRIPT" VARCHAR(3900),
"DEPLOY_SCRIPT" VARCHAR(3900),
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("APP_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."MNT_APP" IS '应用管理';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."APP_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."BACKUP_PATH" IS '备份路径';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."DEPLOY_PATH" IS '部署路径';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."DEPLOY_SCRIPT" IS '部署脚本';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."NAME" IS '应用名称';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."PORT" IS '应用端口';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."START_SCRIPT" IS '启动脚本';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_APP"."UPLOAD_PATH" IS '上传目录';


CREATE UNIQUE  INDEX "INDEX871470091313000" ON "DB_SYSTEM"."MNT_APP"("APP_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."MNT_DATABASE"
(
"DB_ID" VARCHAR(50) NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"JDBC_URL" VARCHAR(255) NOT NULL,
"USER_NAME" VARCHAR(255) NOT NULL,
"PWD" VARCHAR(255) NOT NULL,
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("DB_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."MNT_DATABASE" IS '数据库管理';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."DB_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."JDBC_URL" IS 'jdbc连接';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."NAME" IS '名称';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."PWD" IS '密码';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DATABASE"."USER_NAME" IS '账号';


CREATE UNIQUE  INDEX "INDEX871470069215800" ON "DB_SYSTEM"."MNT_DATABASE"("DB_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."MNT_DEPLOY"
(
"DEPLOY_ID" VARCHAR(32) NOT NULL,
"APP_ID" VARCHAR(32),
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("DEPLOY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."MNT_DEPLOY" IS '部署管理';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY"."APP_ID" IS '应用编号';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY"."DEPLOY_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "FK6SY157PSEOXX4FMCQR1VNVVHY" ON "DB_SYSTEM"."MNT_DEPLOY"("APP_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871470052363200" ON "DB_SYSTEM"."MNT_DEPLOY"("DEPLOY_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."MNT_DEPLOY_HISTORY"
(
"HISTORY_ID" VARCHAR(50) NOT NULL,
"APP_NAME" VARCHAR(255) NOT NULL,
"DEPLOY_DATE" TIMESTAMP(0) NOT NULL,
"DEPLOY_USER" VARCHAR(50) NOT NULL,
"IP" VARCHAR(20) NOT NULL,
"DEPLOY_ID" VARCHAR(32),
NOT CLUSTER PRIMARY KEY("HISTORY_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."MNT_DEPLOY_HISTORY" IS '部署历史管理';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_HISTORY"."APP_NAME" IS '应用名称';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_HISTORY"."DEPLOY_DATE" IS '部署日期';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_HISTORY"."DEPLOY_ID" IS '部署编号';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_HISTORY"."DEPLOY_USER" IS '部署用户';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_HISTORY"."HISTORY_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_HISTORY"."IP" IS '服务器IP';


CREATE UNIQUE  INDEX "INDEX871470027959900" ON "DB_SYSTEM"."MNT_DEPLOY_HISTORY"("HISTORY_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."MNT_DEPLOY_SERVER"
(
"DEPLOY_ID" VARCHAR(32) NOT NULL,
"SERVER_ID" VARCHAR(32) NOT NULL,
NOT CLUSTER PRIMARY KEY("DEPLOY_ID", "SERVER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."MNT_DEPLOY_SERVER" IS '应用与服务器关联';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_SERVER"."DEPLOY_ID" IS '部署ID';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_DEPLOY_SERVER"."SERVER_ID" IS '服务ID';


CREATE  INDEX "FKEAAHA7JEW9A02B3BK9GHOLS53" ON "DB_SYSTEM"."MNT_DEPLOY_SERVER"("SERVER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871470016760600" ON "DB_SYSTEM"."MNT_DEPLOY_SERVER"("DEPLOY_ID" ASC,"SERVER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."MNT_SERVER"
(
"SERVER_ID" VARCHAR(32) NOT NULL,
"ACCOUNT" VARCHAR(50),
"IP" VARCHAR(20),
"NAME" VARCHAR(100),
"PASSWORD" VARCHAR(100),
"PORT" INT,
"CREATE_BY" VARCHAR(255),
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0),
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("SERVER_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."MNT_SERVER" IS '服务器管理';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."ACCOUNT" IS '账号';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."IP" IS 'IP地址';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."NAME" IS '名称';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."PORT" IS '端口';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."SERVER_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."MNT_SERVER"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "IDX_IP" ON "DB_SYSTEM"."MNT_SERVER"("IP" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469987214300" ON "DB_SYSTEM"."MNT_SERVER"("SERVER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_DEPT"
(
"DEPT_ID" VARCHAR(32) NOT NULL,
"PID" VARCHAR(32),
"SUB_COUNT" INT DEFAULT 0 NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"FULL_NAME" VARCHAR(255) NOT NULL,
"CODE" VARCHAR(9),
"DEPT_TYPE" VARCHAR(4) NOT NULL,
"DEPT_SORT" INT DEFAULT 999,
"ENABLED" BIT NOT NULL,
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("DEPT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_DEPT" IS '部门表';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."DEPT_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."DEPT_SORT" IS '排序';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."ENABLED" IS '状态';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."NAME" IS '名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."FULL_NAME" IS '名称全称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."CODE" IS '部门代码';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."DEPT_TYPE" IS '部门类型';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."PID" IS '上级部门';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."SUB_COUNT" IS '子部门数目';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DEPT"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "INDEX871469944279100" ON "DB_SYSTEM"."SYS_DEPT"("PID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "INDEX871469950979100" ON "DB_SYSTEM"."SYS_DEPT"("ENABLED" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469956372600" ON "DB_SYSTEM"."SYS_DEPT"("DEPT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_DICT"
(
"DICT_ID" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(255) NOT NULL,
"DESCRIPTION" VARCHAR(255) NOT NULL,
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("DICT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_DICT" IS '数据字典';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."DICT_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."NAME" IS '字典名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT"."UPDATE_TIME" IS '更新时间';


CREATE UNIQUE  INDEX "INDEX871469926002600" ON "DB_SYSTEM"."SYS_DICT"("DICT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_DICT_DETAIL"
(
"DETAIL_ID" VARCHAR(32) NOT NULL,
"DICT_ID" VARCHAR(32) NOT NULL,
"LABEL" VARCHAR(255) NOT NULL,
"VALUE" VARCHAR(255) NOT NULL,
"DICT_SORT" INT,
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("DETAIL_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_DICT_DETAIL" IS '数据字典详情';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."DETAIL_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."DICT_ID" IS '字典id';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."DICT_SORT" IS '排序';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."LABEL" IS '字典标签';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_DICT_DETAIL"."VALUE" IS '字典值';


CREATE  INDEX "FK5TPKPUTC6D9NBOXOJDBGNPMYB" ON "DB_SYSTEM"."SYS_DICT_DETAIL"("DICT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469901457600" ON "DB_SYSTEM"."SYS_DICT_DETAIL"("DETAIL_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_JOB"
(
"JOB_ID" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(180) NOT NULL,
"ENABLED" BIT NOT NULL,
"JOB_SORT" INT,
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("JOB_ID"),
UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_JOB" IS '岗位表';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."ENABLED" IS '岗位状态';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."JOB_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."JOB_SORT" IS '排序';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."NAME" IS '岗位名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_JOB"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "INDEX871469873144700" ON "DB_SYSTEM"."SYS_JOB"("ENABLED" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469877966000" ON "DB_SYSTEM"."SYS_JOB"("JOB_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_LOG"
(
"LOG_ID" VARCHAR(32) NOT NULL,
"DESCRIPTION" VARCHAR(255) NOT NULL,
"LOG_TYPE" VARCHAR(10) NOT NULL,
"METHOD" VARCHAR(255) NOT NULL,
"PARAMS" TEXT,
"REQUEST_IP" VARCHAR(255),
"TIME" BIGINT,
"USERNAME" VARCHAR(255) NOT NULL,
"ADDRESS" VARCHAR(255),
"BROWSER" VARCHAR(255),
"EXCEPTION_DETAIL" TEXT,
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
NOT CLUSTER PRIMARY KEY("LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_LOG" IS '系统日志';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."ADDRESS" IS '地址';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."BROWSER" IS '浏览器';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."EXCEPTION_DETAIL" IS '异常详细';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."LOG_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."LOG_TYPE" IS '日志类型';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."METHOD" IS '方法名';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."PARAMS" IS '参数';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."REQUEST_IP" IS '请求ip';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."TIME" IS '请求耗时';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_LOG"."USERNAME" IS '操作用户';


CREATE  INDEX "INX_LOG_TYPE" ON "DB_SYSTEM"."SYS_LOG"("LOG_TYPE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "LOG_CREATE_TIME_INDEX" ON "DB_SYSTEM"."SYS_LOG"("CREATE_TIME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469845133100" ON "DB_SYSTEM"."SYS_LOG"("LOG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_MENU"
(
"MENU_ID" VARCHAR(32) NOT NULL,
"PID" VARCHAR(32),
"SUB_COUNT" INT DEFAULT 0 NOT NULL,
"TYPE" INT NOT NULL,
"TITLE" VARCHAR(100) NOT NULL,
"NAME" VARCHAR(100),
"COMPONENT" VARCHAR(255),
"MENU_SORT" INT,
"ICON" VARCHAR(255),
"PATH" VARCHAR(255),
"I_FRAME" BIT NOT NULL,
"CACHE" BIT DEFAULT '0' NOT NULL,
"HIDDEN" BIT DEFAULT '0' NOT NULL,
"PERMISSION" VARCHAR(255),
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("MENU_ID"),
UNIQUE("NAME"),
CONSTRAINT "UNIQ_TITLE" UNIQUE("TITLE")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_MENU" IS '系统菜单';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."CACHE" IS '缓存';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."COMPONENT" IS '组件';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."HIDDEN" IS '隐藏';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."ICON" IS '图标';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."I_FRAME" IS '是否外链';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."MENU_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."MENU_SORT" IS '排序';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."NAME" IS '组件名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."PATH" IS '链接地址';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."PERMISSION" IS '权限';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."PID" IS '上级菜单ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."SUB_COUNT" IS '子菜单数目';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."TITLE" IS '菜单标题';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."TYPE" IS '菜单类型';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_MENU"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "INX_PID" ON "DB_SYSTEM"."SYS_MENU"("PID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469795137000" ON "DB_SYSTEM"."SYS_MENU"("MENU_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_QUARTZ_JOB"
(
"JOB_ID" VARCHAR(32) NOT NULL,
"BEAN_NAME" VARCHAR(255),
"CRON_EXPRESSION" VARCHAR(255),
"IS_PAUSE" BIT,
"JOB_NAME" VARCHAR(255),
"METHOD_NAME" VARCHAR(255),
"PARAMS" VARCHAR(255),
"DESCRIPTION" VARCHAR(255),
"PERSON_IN_CHARGE" VARCHAR(100),
"EMAIL" VARCHAR(100),
"SUB_TASK" VARCHAR(100),
"PAUSE_AFTER_FAILURE" BIT,
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("JOB_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_QUARTZ_JOB" IS '定时任务';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."BEAN_NAME" IS 'Spring Bean名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."CRON_EXPRESSION" IS 'cron 表达式';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."DESCRIPTION" IS '备注';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."EMAIL" IS '报警邮箱';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."IS_PAUSE" IS '状态：1暂停、0启用';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."JOB_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."METHOD_NAME" IS '方法名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."PARAMS" IS '参数';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."PAUSE_AFTER_FAILURE" IS '任务失败后是否暂停';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."PERSON_IN_CHARGE" IS '负责人';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."SUB_TASK" IS '子任务ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_JOB"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "INX_IS_PAUSE" ON "DB_SYSTEM"."SYS_QUARTZ_JOB"("IS_PAUSE" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469752545800" ON "DB_SYSTEM"."SYS_QUARTZ_JOB"("JOB_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_QUARTZ_LOG"
(
"LOG_ID" VARCHAR(32) NOT NULL,
"BEAN_NAME" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"CRON_EXPRESSION" VARCHAR(255),
"EXCEPTION_DETAIL" TEXT,
"IS_SUCCESS" BIT,
"JOB_NAME" VARCHAR(255),
"METHOD_NAME" VARCHAR(255),
"PARAMS" VARCHAR(255),
"TIME" BIGINT,
NOT CLUSTER PRIMARY KEY("LOG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_QUARTZ_LOG" IS '定时任务日志';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."BEAN_NAME" IS 'bean名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."EXCEPTION_DETAIL" IS '异常详情';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."IS_SUCCESS" IS '状态';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."JOB_NAME" IS '任务名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."LOG_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."METHOD_NAME" IS '方法名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."PARAMS" IS '参数';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_QUARTZ_LOG"."TIME" IS '执行耗时';


CREATE UNIQUE  INDEX "INDEX871469726021700" ON "DB_SYSTEM"."SYS_QUARTZ_LOG"("LOG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_ROLE"
(
"ROLE_ID" VARCHAR(32) NOT NULL,
"NAME" VARCHAR(100) NOT NULL,
"LEVEL" INT,
"DESCRIPTION" VARCHAR(255),
"DATA_SCOPE" VARCHAR(255),
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("ROLE_ID"),
UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_ROLE" IS '角色表';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."DATA_SCOPE" IS '数据权限';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."LEVEL" IS '角色级别';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."NAME" IS '名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."ROLE_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLE"."UPDATE_TIME" IS '更新时间';


CREATE  INDEX "ROLE_NAME_INDEX" ON "DB_SYSTEM"."SYS_ROLE"("NAME" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469707741600" ON "DB_SYSTEM"."SYS_ROLE"("ROLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_ROLES_DEPTS"
(
"ROLE_ID" VARCHAR(32) NOT NULL,
"DEPT_ID" VARCHAR(32) NOT NULL,
NOT CLUSTER PRIMARY KEY("ROLE_ID", "DEPT_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_ROLES_DEPTS" IS '角色部门关联';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLES_DEPTS"."DEPT_ID" IS '部门ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLES_DEPTS"."ROLE_ID" IS '角色ID';


CREATE  INDEX "FK7QG6ITN5AJDOA9H9O78V9KSUR" ON "DB_SYSTEM"."SYS_ROLES_DEPTS"("DEPT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469690442300" ON "DB_SYSTEM"."SYS_ROLES_DEPTS"("ROLE_ID" ASC,"DEPT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_ROLES_MENUS"
(
"MENU_ID" VARCHAR(32) NOT NULL,
"ROLE_ID" VARCHAR(32) NOT NULL,
NOT CLUSTER PRIMARY KEY("MENU_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_ROLES_MENUS" IS '角色菜单关联';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLES_MENUS"."MENU_ID" IS '菜单ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_ROLES_MENUS"."ROLE_ID" IS '角色ID';


CREATE  INDEX "FKCNGG2QADOJHI3A651A5ADKVBQ" ON "DB_SYSTEM"."SYS_ROLES_MENUS"("ROLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469673196000" ON "DB_SYSTEM"."SYS_ROLES_MENUS"("MENU_ID" ASC,"ROLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_USER"
(
"USER_ID" VARCHAR(32) NOT NULL,
"DEPT_ID" VARCHAR(32),
"USERNAME" VARCHAR(180) NOT NULL,
"NICK_NAME" VARCHAR(255),
"GENDER" VARCHAR(2),
"PHONE" VARCHAR(255),
"EMAIL" VARCHAR(180),
"AVATAR_NAME" VARCHAR(255),
"AVATAR_PATH" VARCHAR(255),
"PASSWORD" VARCHAR(255) NOT NULL,
"IS_ADMIN" BIT DEFAULT '0' NOT NULL,
"ENABLED" BIT DEFAULT '1' NOT NULL,
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"PWD_RESET_TIME" TIMESTAMP(0),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("USER_ID"),
CONSTRAINT "UK_KPUBOS9GC2CVTKB0THKTKBKES" UNIQUE("EMAIL"),
CONSTRAINT "UNIQ_USERNAME" UNIQUE("USERNAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_USER" IS '系统用户';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."AVATAR_NAME" IS '头像地址';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."AVATAR_PATH" IS '头像真实路径';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."DEPT_ID" IS '部门名称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."ENABLED" IS '状态：1启用、0禁用';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."GENDER" IS '性别';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."IS_ADMIN" IS '是否为admin账号';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."NICK_NAME" IS '昵称';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."PHONE" IS '手机号码';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."PWD_RESET_TIME" IS '修改密码的时间';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."USERNAME" IS '用户名';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USER"."USER_ID" IS 'ID';


CREATE  INDEX "FK5RWMRYNY6JTHAAXKOGOWNKNQP" ON "DB_SYSTEM"."SYS_USER"("DEPT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE  INDEX "INX_ENABLED" ON "DB_SYSTEM"."SYS_USER"("ENABLED" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469630726000" ON "DB_SYSTEM"."SYS_USER"("USER_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_USERS_JOBS"
(
"USER_ID" VARCHAR(32) NOT NULL,
"JOB_ID" VARCHAR(32) NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_ID", "JOB_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_USERS_JOBS" IS '用户岗位关联';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USERS_JOBS"."JOB_ID" IS '岗位ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USERS_JOBS"."USER_ID" IS '用户ID';


CREATE UNIQUE  INDEX "INDEX871469605847000" ON "DB_SYSTEM"."SYS_USERS_JOBS"("USER_ID" ASC,"JOB_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."SYS_USERS_ROLES"
(
"USER_ID" VARCHAR(32) NOT NULL,
"ROLE_ID" VARCHAR(32) NOT NULL,
NOT CLUSTER PRIMARY KEY("USER_ID", "ROLE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."SYS_USERS_ROLES" IS '用户角色关联';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USERS_ROLES"."ROLE_ID" IS '角色ID';
COMMENT ON COLUMN "DB_SYSTEM"."SYS_USERS_ROLES"."USER_ID" IS '用户ID';


CREATE  INDEX "FKQ4EQ273L04BPU4EFJ0JD0JB98" ON "DB_SYSTEM"."SYS_USERS_ROLES"("ROLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;
CREATE UNIQUE  INDEX "INDEX871469591142600" ON "DB_SYSTEM"."SYS_USERS_ROLES"("USER_ID" ASC,"ROLE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"
(
"CONFIG_ID" VARCHAR(32) NOT NULL,
"APP_ID" VARCHAR(255),
"CHARSET" VARCHAR(255),
"FORMAT" VARCHAR(255),
"GATEWAY_URL" VARCHAR(255),
"NOTIFY_URL" VARCHAR(255),
"PRIVATE_KEY" TEXT,
"PUBLIC_KEY" TEXT,
"RETURN_URL" VARCHAR(255),
"SIGN_TYPE" VARCHAR(255),
"SYS_SERVICE_PROVIDER_ID" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("CONFIG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."TOOL_ALIPAY_CONFIG" IS '支付宝配置类';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."APP_ID" IS '应用ID';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."CHARSET" IS '编码';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."CONFIG_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."FORMAT" IS '类型 固定格式json';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."GATEWAY_URL" IS '网关地址';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."NOTIFY_URL" IS '异步回调';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."PRIVATE_KEY" IS '私钥';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."PUBLIC_KEY" IS '公钥';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."RETURN_URL" IS '回调地址';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."SIGN_TYPE" IS '签名方式';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"."SYS_SERVICE_PROVIDER_ID" IS '商户号';


CREATE UNIQUE  INDEX "INDEX871469554212200" ON "DB_SYSTEM"."TOOL_ALIPAY_CONFIG"("CONFIG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."TOOL_EMAIL_CONFIG"
(
"CONFIG_ID" VARCHAR(32) NOT NULL,
"FROM_USER" VARCHAR(255),
"HOST" VARCHAR(255),
"PASS" VARCHAR(255),
"PORT" VARCHAR(255),
"USER" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("CONFIG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."TOOL_EMAIL_CONFIG" IS '邮箱配置';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_EMAIL_CONFIG"."CONFIG_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_EMAIL_CONFIG"."FROM_USER" IS '收件人';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_EMAIL_CONFIG"."HOST" IS '邮件服务器SMTP地址';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_EMAIL_CONFIG"."PASS" IS '密码';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_EMAIL_CONFIG"."PORT" IS '端口';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_EMAIL_CONFIG"."USER" IS '发件者用户名';


CREATE UNIQUE  INDEX "INDEX871469534621200" ON "DB_SYSTEM"."TOOL_EMAIL_CONFIG"("CONFIG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."TOOL_LOCAL_STORAGE"
(
"STORAGE_ID" VARCHAR(32) NOT NULL,
"REAL_NAME" VARCHAR(255),
"NAME" VARCHAR(255),
"SUFFIX" VARCHAR(255),
"PATH" VARCHAR(255),
"TYPE" VARCHAR(255),
"SIZE" VARCHAR(100),
"CREATE_BY" VARCHAR(255) NOT NULL,
"UPDATE_BY" VARCHAR(255),
"CREATE_TIME" TIMESTAMP(0) NOT NULL,
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("STORAGE_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."TOOL_LOCAL_STORAGE" IS '本地存储';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."CREATE_BY" IS '创建者';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."CREATE_TIME" IS '创建日期';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."NAME" IS '文件名';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."PATH" IS '路径';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."REAL_NAME" IS '文件真实的名称';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."SIZE" IS '大小';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."STORAGE_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."SUFFIX" IS '后缀';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."TYPE" IS '类型';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."UPDATE_BY" IS '更新者';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_LOCAL_STORAGE"."UPDATE_TIME" IS '更新时间';


CREATE UNIQUE  INDEX "INDEX871469510565100" ON "DB_SYSTEM"."TOOL_LOCAL_STORAGE"("STORAGE_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."TOOL_QINIU_CONFIG"
(
"CONFIG_ID" VARCHAR(32) NOT NULL,
"ACCESS_KEY" TEXT,
"BUCKET" VARCHAR(255),
"HOST" VARCHAR(255) NOT NULL,
"SECRET_KEY" TEXT,
"TYPE" VARCHAR(255),
"ZONE" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("CONFIG_ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."TOOL_QINIU_CONFIG" IS '七牛云配置';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."ACCESS_KEY" IS 'accessKey';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."BUCKET" IS 'Bucket 识别符';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."CONFIG_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."HOST" IS '外链域名';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."SECRET_KEY" IS 'secretKey';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."TYPE" IS '空间类型';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONFIG"."ZONE" IS '机房';


CREATE UNIQUE  INDEX "INDEX871469492134000" ON "DB_SYSTEM"."TOOL_QINIU_CONFIG"("CONFIG_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "DB_SYSTEM"."TOOL_QINIU_CONTENT"
(
"CONTENT_ID" VARCHAR(32) NOT NULL,
"BUCKET" VARCHAR(255),
"NAME" VARCHAR(180),
"SIZE" VARCHAR(255),
"TYPE" VARCHAR(255),
"URL" VARCHAR(255),
"SUFFIX" VARCHAR(255),
"UPDATE_TIME" TIMESTAMP(0),
NOT CLUSTER PRIMARY KEY("CONTENT_ID"),
CONSTRAINT "UNIQ_NAME" UNIQUE("NAME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DB_SYSTEM"."TOOL_QINIU_CONTENT" IS '七牛云文件存储';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."BUCKET" IS 'Bucket 识别符';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."CONTENT_ID" IS 'ID';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."NAME" IS '文件名称';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."SIZE" IS '文件大小';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."SUFFIX" IS '文件后缀';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."TYPE" IS '文件类型：私有或公开';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."UPDATE_TIME" IS '上传或同步的时间';
COMMENT ON COLUMN "DB_SYSTEM"."TOOL_QINIU_CONTENT"."URL" IS '文件url';


CREATE UNIQUE  INDEX "PRIMARY" ON "DB_SYSTEM"."TOOL_QINIU_CONTENT"("CONTENT_ID" ASC) STORAGE(ON "MAIN", CLUSTERBTR) ;


-- ----------------------------
-- Records of SYS_USER
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_USER" VALUES ('1', '1685939356307636225', 'admin', '系统管理员', '男', '18888888888', '201507802@qq.com', 'avatar-20230731033626454.png', 'C:\eladmin\avatar\avatar-20230731033626454.png', '$2a$10$Egp1/gvFlt7zhlXVfEFw4OfWQCGPw0ClmMcc6FjTnvXNRVf9zdMRa', '1', '1', 'admin', 'admin', TO_TIMESTAMP('2020-05-03 16:38:31 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2018-08-23 09:11:56 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-09-05 10:43:31 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
-- ----------------------------
-- Records of SYS_USERS_JOBS
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_USERS_JOBS" VALUES ('1', '11');
-- ----------------------------
-- Records of SYS_USERS_ROLES
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_USERS_ROLES" VALUES ('1', '1');
-- ----------------------------
-- Records of SYS_MENU
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('1', NULL, '7', '0', '系统管理', NULL, NULL, '1', 'system', 'system', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-18 15:11:29 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('10', NULL, '5', '0', '组件管理', NULL, NULL, '50', 'zujian', 'components', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-19 13:38:16 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('102', '97', '0', '2', '删除', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'deployHistory:del', 'admin', NULL, TO_TIMESTAMP('2019-11-17 09:32:48 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('103', '92', '0', '2', '服务器新增', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'serverDeploy:add', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:08:33 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('104', '92', '0', '2', '服务器编辑', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'serverDeploy:edit', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:08:57 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('105', '92', '0', '2', '服务器删除', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'serverDeploy:del', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:09:15 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('106', '93', '0', '2', '应用新增', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'app:add', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:10:03 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('107', '93', '0', '2', '应用编辑', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'app:edit', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:10:28 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('108', '93', '0', '2', '应用删除', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'app:del', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:10:55 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('109', '94', '0', '2', '部署新增', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'deploy:add', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:11:22 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('11', '10', '0', '1', '图标库', 'Icons', 'components/icons/index', '51', 'icon', 'icon', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-19 13:38:49 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('110', '94', '0', '2', '部署编辑', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'deploy:edit', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:11:41 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('111', '94', '0', '2', '部署删除', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'deploy:del', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:12:01 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('112', '98', '0', '2', '数据库新增', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'database:add', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:12:43 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('113', '98', '0', '2', '数据库编辑', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'database:edit', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:12:58 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('114', '98', '0', '2', '数据库删除', NULL, NULL, '999', NULL, NULL, '0', '0', '0', 'database:del', 'admin', NULL, TO_TIMESTAMP('2019-11-17 11:13:14 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('116', '36', '0', '1', '生成预览', 'Preview', 'generator/preview', '999', 'java', 'generator/preview/:tableName', '0', '1', '1', NULL, 'admin', NULL, TO_TIMESTAMP('2019-11-26 14:54:36 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('14', '36', '0', '1', '邮件工具', 'Email', 'tools/email/index', '35', 'email', 'email', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-27 10:13:09 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('15', '10', '0', '1', '富文本', 'Editor', 'components/Editor', '52', 'fwb', 'tinymce', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-27 11:58:25 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('18', '36', '3', '1', '存储管理', 'Storage', 'tools/storage/index', '34', 'qiniu', 'storage', '0', '0', '0', 'storage:list', 'admin', NULL, TO_TIMESTAMP('2018-12-31 11:12:15 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('19', '36', '0', '1', '支付宝工具', 'AliPay', 'tools/aliPay/index', '37', 'alipay', 'aliPay', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-31 14:52:38 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('2', '1', '3', '1', '用户管理', 'User', 'system/user/index', '2', 'peoples', 'user', '0', '0', '0', 'user:list', 'admin', NULL, TO_TIMESTAMP('2018-12-18 15:14:44 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('21', NULL, '2', '0', '多级菜单', NULL, NULL, '900', 'menu', 'nested', '0', '0', '0', NULL, 'admin', 'admin', TO_TIMESTAMP('2019-01-04 16:22:03 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-06-21 17:27:35 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('22', '21', '2', '0', '二级菜单1', NULL, NULL, '999', 'menu', 'menu1', '0', '0', '0', NULL, 'admin', 'admin', TO_TIMESTAMP('2019-01-04 16:23:29 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-06-21 17:27:20 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('23', '21', '0', '1', '二级菜单2', NULL, 'nested/menu2/index', '999', 'menu', 'menu2', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-01-04 16:23:57 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('24', '22', '0', '1', '三级菜单1', 'Test', 'nested/menu1/menu1-1', '999', 'menu', 'menu1-1', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-01-04 16:24:48 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('27', '22', '0', '1', '三级菜单2', NULL, 'nested/menu1/menu1-2', '999', 'menu', 'menu1-2', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-01-07 17:27:32 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('28', '1', '3', '1', '任务调度', 'Timing', 'system/timing/index', '999', 'timing', 'timing', '0', '0', '0', 'timing:list', 'admin', NULL, TO_TIMESTAMP('2019-01-07 20:34:40 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('3', '1', '3', '1', '角色管理', 'Role', 'system/role/index', '3', 'role', 'role', '0', '0', '0', 'roles:list', 'admin', NULL, TO_TIMESTAMP('2018-12-18 15:16:07 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('30', '36', '0', '1', '代码生成', 'GeneratorIndex', 'generator/index', '32', 'dev', 'generator', '0', '1', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-01-11 15:45:55 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('32', '6', '0', '1', '异常日志', 'ErrorLog', 'monitor/log/errorLog', '12', 'error', 'errorLog', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-01-13 13:49:03 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('33', '10', '0', '1', 'Markdown', 'Markdown', 'components/MarkDown', '53', 'markdown', 'markdown', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-03-08 13:46:44 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('34', '10', '0', '1', 'Yaml编辑器', 'YamlEdit', 'components/YamlEdit', '54', 'dev', 'yaml', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-03-08 15:49:40 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('35', '1', '3', '1', '部门管理', 'Dept', 'system/dept/index', '6', 'dept', 'dept', '0', '0', '0', 'dept:list', 'admin', NULL, TO_TIMESTAMP('2019-03-25 09:46:00 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('36', NULL, '7', '0', '系统工具', NULL, NULL, '30', 'sys-tools', 'sys-tools', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-03-29 10:57:35 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('37', '1', '3', '1', '岗位管理', 'Job', 'system/job/index', '7', 'Steve-Jobs', 'job', '0', '0', '0', 'job:list', 'admin', NULL, TO_TIMESTAMP('2019-03-29 13:51:18 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('38', '36', '0', '1', '接口文档', 'Swagger', 'tools/swagger/index', '36', 'swagger', 'swagger2', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-03-29 19:57:53 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('39', '1', '3', '1', '字典管理', 'Dict', 'system/dict/index', '8', 'dictionary', 'dict', '0', '0', '0', 'dict:list', 'admin', NULL, TO_TIMESTAMP('2019-04-10 11:49:04 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('41', '6', '0', '1', '在线用户', 'OnlineUser', 'monitor/online/index', '10', 'Steve-Jobs', 'online', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-10-26 22:08:43 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('44', '2', '0', '2', '用户新增', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'user:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 10:59:46 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('45', '2', '0', '2', '用户编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'user:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 11:00:08 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('46', '2', '0', '2', '用户删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'user:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 11:00:23 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('48', '3', '0', '2', '角色创建', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'roles:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:45:34 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('49', '3', '0', '2', '角色修改', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'roles:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:46:16 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('5', '1', '3', '1', '菜单管理', 'Menu', 'system/menu/index', '5', 'menu', 'menu', '0', '0', '0', 'menu:list', 'admin', NULL, TO_TIMESTAMP('2018-12-18 15:17:28 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('50', '3', '0', '2', '角色删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'roles:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:46:51 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('52', '5', '0', '2', '菜单新增', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'menu:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:55:07 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('53', '5', '0', '2', '菜单编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'menu:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:55:40 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('54', '5', '0', '2', '菜单删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'menu:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:56:00 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('56', '35', '0', '2', '部门新增', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'dept:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:57:09 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('57', '35', '0', '2', '部门编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'dept:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:57:27 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('58', '35', '0', '2', '部门删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'dept:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:57:41 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('6', NULL, '5', '0', '系统监控', NULL, NULL, '10', 'monitor', 'monitor', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-18 15:17:48 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('60', '37', '0', '2', '岗位新增', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'job:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:58:27 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('61', '37', '0', '2', '岗位编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'job:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:58:45 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('62', '37', '0', '2', '岗位删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'job:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 12:59:04 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('64', '39', '0', '2', '字典新增', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'dict:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:00:17 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('65', '39', '0', '2', '字典编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'dict:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:00:42 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('66', '39', '0', '2', '字典删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'dict:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:00:59 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('7', '6', '0', '1', '操作日志', 'Log', 'monitor/log/index', '11', 'log', 'logs', '0', '1', '0', NULL, 'admin', 'admin', TO_TIMESTAMP('2018-12-18 15:18:26 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-06-06 13:11:57 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('73', '28', '0', '2', '任务新增', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'timing:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:07:28 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('74', '28', '0', '2', '任务编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'timing:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:07:41 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('75', '28', '0', '2', '任务删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'timing:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:07:54 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('77', '18', '0', '2', '上传文件', NULL, NULL, '2', NULL, NULL, '0', '0', '0', 'storage:add', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:09:09 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('78', '18', '0', '2', '文件编辑', NULL, NULL, '3', NULL, NULL, '0', '0', '0', 'storage:edit', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:09:22 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('79', '18', '0', '2', '文件删除', NULL, NULL, '4', NULL, NULL, '0', '0', '0', 'storage:del', 'admin', NULL, TO_TIMESTAMP('2019-10-29 13:09:34 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('80', '6', '0', '1', '服务监控', 'ServerMonitor', 'monitor/server/index', '14', 'codeConsole', 'server', '0', '0', '0', 'monitor:list', 'admin', 'admin', TO_TIMESTAMP('2019-11-07 13:06:39 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-05-04 18:20:50 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('82', '36', '0', '1', '生成配置', 'GeneratorConfig', 'generator/config', '33', 'dev', 'generator/config/:tableName', '0', '1', '1', NULL, 'admin', NULL, TO_TIMESTAMP('2019-11-17 20:08:56 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('83', '10', '0', '1', '图表库', 'Echarts', 'components/Echarts', '50', 'chart', 'echarts', '0', '1', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-11-21 09:04:32 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('9', '6', '0', '1', 'SQL监控', 'Sql', 'monitor/sql/index', '18', 'sqlMonitor', 'druid', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2018-12-18 15:19:34 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('90', NULL, '5', '1', '运维管理', 'Mnt', NULL, '20', 'mnt', 'mnt', '0', '0', '0', NULL, 'admin', NULL, TO_TIMESTAMP('2019-11-09 10:31:08 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('92', '90', '3', '1', '服务器', 'ServerDeploy', 'mnt/server/index', '22', 'server', 'mnt/serverDeploy', '0', '0', '0', 'serverDeploy:list', 'admin', NULL, TO_TIMESTAMP('2019-11-10 10:29:25 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('93', '90', '3', '1', '应用管理', 'App', 'mnt/app/index', '23', 'app', 'mnt/app', '0', '0', '0', 'app:list', 'admin', NULL, TO_TIMESTAMP('2019-11-10 11:05:16 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('94', '90', '3', '1', '部署管理', 'Deploy', 'mnt/deploy/index', '24', 'deploy', 'mnt/deploy', '0', '0', '0', 'deploy:list', 'admin', NULL, TO_TIMESTAMP('2019-11-10 15:56:55 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('97', '90', '1', '1', '部署备份', 'DeployHistory', 'mnt/deployHistory/index', '25', 'backup', 'mnt/deployHistory', '0', '0', '0', 'deployHistory:list', 'admin', NULL, TO_TIMESTAMP('2019-11-10 16:49:44 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
INSERT INTO "DB_SYSTEM"."SYS_MENU" VALUES ('98', '90', '3', '1', '数据库管理', 'Database', 'mnt/database/index', '26', 'database', 'mnt/database', '0', '0', '0', 'database:list', 'admin', NULL, TO_TIMESTAMP('2019-11-10 20:40:04 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), NULL);
-- ----------------------------
-- Records of SYS_QUARTZ_JOB
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_QUARTZ_JOB" VALUES ('2', 'testTask', '0/5 * * * * ?', '1', '测试1', 'run1', 'test', '带参测试，多参使用json', '测试', NULL, NULL, NULL, 'admin', 'admin', TO_TIMESTAMP('2019-08-22 14:08:29 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-05-24 13:58:33 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_QUARTZ_JOB" VALUES ('3', 'testTask', '0/5 * * * * ?', '1', '测试', 'run', NULL, '不带参测试', 'Zheng Jie', NULL, '5,6', '1', 'admin', 'admin', TO_TIMESTAMP('2019-09-26 16:44:39 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-05-24 14:48:12 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_QUARTZ_JOB" VALUES ('5', 'Test', '0/5 * * * * ?', '1', '任务告警测试', 'run', NULL, '测试', 'test', NULL, NULL, '1', 'admin', 'admin', TO_TIMESTAMP('2020-05-05 20:32:41 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-05-05 20:36:13 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_QUARTZ_JOB" VALUES ('6', 'testTask', '0/5 * * * * ?', '1', '测试3', 'run2', NULL, '测试3', 'Zheng Jie', NULL, NULL, '1', 'admin', 'admin', TO_TIMESTAMP('2020-05-05 20:35:41 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-05-05 20:36:07 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
-- ----------------------------
-- Records of SYS_ROLE
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_ROLE" VALUES ('1', '超级管理员', '1', '-', '全部', 'admin', 'admin', TO_TIMESTAMP('2018-11-23 11:04:37 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-08-06 16:10:24 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
INSERT INTO "DB_SYSTEM"."SYS_ROLE" VALUES ('2', '普通用户', '2', '-', '本级', 'admin', 'admin', TO_TIMESTAMP('2018-11-23 13:09:06 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'), TO_TIMESTAMP('2020-09-05 10:45:12 ', 'SYYYY-MM-DD HH24:MI:SS:FF9'));
-- ----------------------------
-- Records of SYS_ROLES_MENUS
-- ----------------------------
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('1', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('1', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('10', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('10', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('102', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('103', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('104', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('105', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('106', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('107', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('108', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('109', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('11', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('11', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('110', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('111', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('112', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('113', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('114', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('116', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('116', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('120', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('14', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('14', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('15', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('15', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('18', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('19', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('19', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('2', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('2', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('21', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('21', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('22', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('22', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('23', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('23', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('24', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('24', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('27', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('27', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('28', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('3', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('30', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('30', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('32', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('32', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('33', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('33', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('34', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('34', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('35', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('36', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('36', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('37', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('38', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('39', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('41', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('44', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('45', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('46', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('48', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('49', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('5', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('50', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('52', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('53', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('54', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('56', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('57', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('58', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('6', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('6', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('60', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('61', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('62', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('64', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('65', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('66', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('7', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('7', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('73', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('74', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('75', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('77', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('78', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('79', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('80', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('80', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('82', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('82', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('83', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('83', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('9', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('9', '2');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('90', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('92', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('93', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('94', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('97', '1');
INSERT INTO "DB_SYSTEM"."SYS_ROLES_MENUS" VALUES ('98', '1');
